### ISSUE TITLE
autobumper is being caught by disboard.

### ISSUE THREAD

**Issue by LightOfRauru** [Theblockbuster1/disboard-auto-bump#5] opened 2020-09-26 18:22 UTC
this script is being caught by disboard. there needs to be bigger more random gaps in the bump cycle to avoid detection. maybe add a regular 8-10 hour interval to simulate a sleep cycle.

**Comment by Theblockbuster1** [comment] 2020-09-26 18:37
If you want you can change the times yourself, feel free to edit the number at [content.js:78](https://github.com/Theblockbuster1/disboard-auto-bump/blob/master/content.js#L78). Also kinda duplicate of #2.

**Closed by Theblockbuster1** 2020-09-26 18:37 UTC
