### ISSUE TITLE
Bumps once then stops

### ISSUE THREAD

**Issue by Evan933** [Theblockbuster1/disboard-auto-bump#16] opened 2021-07-05 04:58 UTC
Hi, the autobumper was working great until it stopped for some reason. When I start the autobump it bumps once then opens a new tab to https://disboard.org/dashboard/servers and then the timer goes blank --:--:-- and doesn't autobump anymore. I tried reinstalling the plugin but it doesn't change anything.

**Comment by himyfriendmynameisjeff** [comment] 2021-07-07 07:39
Found out, disboard issue, not the auto bump.

**Comment by alexgurrola** [comment] 2021-07-07 20:24
This is almost certainly happening because of the `target="_blank"` on the bump link.

You can remove that from the tab by running the following code in your dev console:

```js
document.getElementById('bumpme').removeAttribute('target')
```

I'm running that code in a tab right now to confirm it fixes the issue, so I'll check back here in a couple hours.

**Comment by alexgurrola** [comment] 2021-07-07 22:30
The code above has now been tested and I can confirm that it does fix this issue.  I will provide a couple more solutions and wrap this up.

This code will remove all link targets on a page, so all links are unable to force a new tab to open:

```js
Array.from(document.querySelectorAll('a[target]')).forEach(e => e.removeAttribute('target'))
```

This extension claims to do the same thing, without any hassle:

https://chrome.google.com/webstore/detail/death-to-blank/gneobebnilffgkejpfhlgkmpkipgbcno?hl=en

I'm running the `Death To _blank` extension in a tab right now to confirm it's an equivalent fix for this issue, so I'll circle back here in a couple hours.

**Comment by Evan933** [comment] 2021-07-07 23:49
thank you very much

**Comment by alexgurrola** [comment] 2021-07-08 02:13
@Evan933 no problem

**Comment by alexgurrola** [comment] 2021-07-08 02:15
I tested the extension and it failed to work.  The code I created for the console all work properly, though.

**Comment by alexgurrola** [comment] 2021-07-08 02:17
@Theblockbuster1 Are you able to run the code in my [snippet ](https://github.com/Theblockbuster1/disboard-auto-bump/issues/16#issuecomment-875907983)directly inside the extension?

**Comment by Theblockbuster1** [comment] 2021-07-08 14:45
Thanks for all of your contributions, I'm releasing a fix now :)

**Closed** 2021-07-08 14:50 UTC
Labels: bug
